### ISSUE TITLE
错字

### ISSUE THREAD

**Issue by CyrusYip** [residualsun1/Residualsun#30]
https://guozheng.rbind.io/posts/2023/12/talk-to-chatgpt-about-glasses/

ChatGPT 在文中拼写错了。看你想自己改错字，我就不直接给你提交修改了。

**Comment by residualsun1** [comment]
嗯👌，这也是一个细节。

**Comment by CyrusYip** [comment]
> 敬畏阅读，相信“阅读是一座随身携带的避难所”。。
>
> https://guozheng.rbind.io/about/

多了个句号。

**Comment by residualsun1** [comment]
已修改。

**Comment by CyrusYip** [comment]
> 2023年5月28日 中午，按照统计之都的帖子成功搭建了自己的第一个博客网站，主题是anatole
>
> 2023年6月5日 凌晨，更换博客主题hugo-tania
>
> 2023年6月6日 下午，更换博客主题hugo-theme-mini

似乎缺了句号？

---

> - **好音乐**。
> - **喜欢R的可视化**。
> - **敬畏阅读**，
> - **喜欢跑步**。

列表条目逗号和句号不一致。

**Comment by residualsun1** [comment]
已修改，顺便全盘更新了“关于”:-)

**Comment by CyrusYip** [comment]
https://guozheng.rbind.io/posts/2024/03/cherish-field-read-morocco/

不止一处引号反了。

![image](https://github.com/residualsun1/Residualsun/assets/60951091/19492471-9c13-4e6d-8995-a4b925aa4d94)

**Comment by residualsun1** [comment]
哭了，我的草稿打在notion，notion上看不出双引号。

![](https://github.com/residualsun1/Images-of-blog/blob/bd82e5364ec72c42a107efafeda97220ebfeb0f6/brakect.png?raw=true)

我在自己的网页上看，也看不出引号。

![](https://github.com/residualsun1/Images-of-blog/blob/bd82e5364ec72c42a107efafeda97220ebfeb0f6/brakect2.png?raw=true)

不过在Rstudio中是能看出来的，之后可以在Rstudio中再检查一遍，正好还可以试试建立分支修改文章再合并。

**Comment by CyrusYip** [comment]
原来如此，我之前一直不理解怎么会有人打反引号。

浏览器的勉强能看。开引号底下较粗，往右上角变细。闭引号顶上较粗，往左下角变细。

![image](https://github.com/residualsun1/Residualsun/assets/60951091/882a449d-8289-46d2-b5e7-1a25d575306f)

Notion 那个我放很大都看着差不多，也许该换个字体。

你改好之后关掉这个 Issue 就行啦。
