### ISSUE TITLE
链接换行时下边框没跟着

### ISSUE THREAD

**Issue by CyrusYip** [residualsun1/Residualsun#35]
https://guozheng.rbind.io/posts/2024/01/how-forest-think/

手机页面：

![image](https://github.com/residualsun1/Residualsun/assets/60951091/c5f2d6ac-6155-470a-b791-7bcd9026c319)

原因：https://github.com/residualsun1/Residualsun/blob/5197a80933b9c36436b41065b4ff44b38fc4f8dc/themes/hugo-theme-mini/static/css/style.css#L440

去掉这行代码链接就变回内联元素了。

**Comment by residualsun1** [comment]
事情是这样滴：我觉得益辉的超链接文本响应方式比较明显（当鼠标移动到超链接上时，文本会稍微动一动），就悄悄翻去益辉仓库看了一下，但没弄懂怎么实现。和ChatGPT说想让超链接文本响应时浮动一下，它给了我几个代码，我折腾了一下发现需要display: inline-block才行。

还没想好怎么解决，要是删掉就没有浮动效果了。

**Comment by CyrusYip** [comment]
> 我折腾了一下发现需要display: inline-block才行。

因为 transition 只对块状元素起作用，inline-block 也是块状元素，但是使用块状元素边框就是一条在下面了。

你用浏览器右击链接，点击 Inspect，在 style 那边勾上 `:hover`。这样就看到他用的样式了。

![image](https://github.com/residualsun1/Residualsun/assets/60951091/a5314ba8-106e-4314-97f0-f05d91bffa4f)

**Comment by residualsun1** [comment]
调成功了！十分感谢^^！！

**Comment by CyrusYip** [comment]
[现在](https://github.com/residualsun1/Residualsun/commit/3ed071073476fd80b948efecaf7053341674c1ce)首页标题链接的效果不对，你之前添加在  `<a>` 标签的 `transition` 和 `transform` 要删掉。

例子：

https://github.com/residualsun1/Residualsun/blame/3ed071073476fd80b948efecaf7053341674c1ce/themes/hugo-theme-mini/static/css/style.css#L328-L337

**Comment by residualsun1** [comment]
原来是想保留部分浮动的，因为标题不会太长，不过全局设置悬停字体微动后两个效果混在一起怪怪的，最后还是决定全部只用字体微动。

**Comment by CyrusYip** [comment]
`:not(.logo)` 是益辉那个主题专用的，我帮你删了。https://github.com/residualsun1/Residualsun/pull/36

**Comment by residualsun1** [comment]
已merge（我以为这也可以防止我博客的图片logo轻微移动） :D

**Comment by CyrusYip** [comment]
> 我以为这也可以防止我博客的图片logo轻微移动

主页的头像吗？我看似乎没有问题。

**Comment by residualsun1** [comment]
确实没啥影响（当时是有点偷懒思考，觉得一起写上会更保险）
