### ISSUE TITLE
协议的年份和名字不对

### ISSUE THREAD

**Issue by CyrusYip** [residualsun1/Residualsun#53]
`Copyright (c) 2014 Steve Francia` 应该是你从别的地方拿来用的吧。

**Comment by residualsun1** [comment]
这个是我下载模板之后就有的，应该是默认的，但我一直没搞懂MIT license干啥用的，以及对我的博客有啥影响，就没咋管了，你不提的话我也不知道。如果要修改的话，需要咋改？

**Comment by CyrusYip** [comment]
开源协议就是规定别人能怎么用你的代码，MIT 是比较宽松的协议，别人用你代码只需要附上一样的协议。常见协议的介绍可以看 https://choosealicense.com/licenses/ 。

年份一般是第一个提交的时间，2024。名字就写你自己的。

**Comment by residualsun1** [comment]
好嘞，已修改✍️。
