### ISSUE TITLE
cleaning-bobo -> cleaner-bobo

### ISSUE THREAD

**Issue by CyrusYip** [residualsun1/Residualsun#54]
https://github.com/residualsun1/Residualsun/blob/afa586a73c34232e5d5014a5c769d79466e96f28/content/posts/2024-05-07-cleaning-bobo.md?plain=1#L5

cleaning bobo 可以解读为把阿伯清理走，改为 cleaner 意思就清除了。bobo 可以改成 uncle。

**Comment by residualsun1** [comment]
已修改。（心虚）没想到还是引起误解了😂，老实交代，想slug的时候心不在焉了。
