### ISSUE TITLE
音乐播放器在暗色模式下颜色不对

### ISSUE THREAD

**Issue by CyrusYip** [residualsun1/Residualsun#64]
<details>
  <summary>有点惊悚的封面图片</summary>
  
  ![Screenshot_20241017_233632](https://github.com/user-attachments/assets/1e7dd0fa-3822-4695-b30c-f7c9877d5675)
</details>

**Comment by residualsun1** [comment]
这是加了暗色模式后的硬伤（无奈），我还没整明白啥回事，按照益辉的[帖子](https://yihui.org/en/2023/09/dark-mode/)贴的代码来设置，我的头像图片没有受到影响，不会变色。

`@media (prefers-color-scheme: dark) {
  html, img, video, iframe {
    filter: invert(1);
  }
  body {
    background-color: white;
  }
}`

但引入的Aplayer播放器的图片好像不行。

**Comment by CyrusYip** [comment]
你对着播放器右击后点 Inspect，可以看到图片不是用 img 显示的。

```
<div class="aplayer-pic" style="background-image: url(&quot;https://cdn.jsdelivr.net/gh/residualsun1/blog-static/images/sound/SABINA之淚.jpg&quot;);background-color: #f8f4fc;">
```

https://github.com/residualsun1/Residualsun/blob/e2288d5852deb24f7c642142ac178a403d696525/themes/hugo-theme-mini/static/css/style.css#L777

我用的 Hugo 0.135.0 运行不了你的网站，你试试把这行代码改成：

```
html, img, video, iframe, .aplayer {
```

---

顺便说一下，emoji 在暗色模式下也是异常的。https://github.com/yihui/hugo-paged/issues/7

**Comment by residualsun1** [comment]
太好了，这下可解决了！我今早试着自己修改的时候，加过aplayer，还加过aplayer-pic，但就是没加上前面的‘.’，也没有用‘,’分隔开。

> 顺便说一下，emoji 在暗色模式下也是异常的。https://github.com/yihui/hugo-paged/issues/7

暗色emoji看起来也有点阴间+滑稽😂，不过我博客里几乎用不上emoji。我之前看过益辉的《[如果没有了表情包，我们还会不会说人话](https://yihui.org/cn/2017/09/emoji/)》，所以就开始不自觉地克制表情包的使用了，包括emoji。不过我觉得这种克制有益，特别是因为我在微信上不得不用表情包，总担心自己只有文字无法让对方感受到我的意思。可能是因为微信的交流太碎片了，这逐渐让我觉得没有表情包就没法和人交流。

**Comment by CyrusYip** [comment]
> 暗色emoji看起来也有点阴间+滑稽😂

确实滑稽，页面底下的红心变成青心了，哈哈。
